import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const baseURL = process.env.BROWSER_TEST_URL || 'http://localhost:3000';
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
page.setDefaultTimeout(25000);
const errors = []; page.on('pageerror', error => errors.push(error.message));
const taskId = '721b1999-1111-4111-8111-111111111111';
const task = {id:taskId, kind:'research', context:{}, objective:'Investigate early retreats', acceptance_criteria:'Find the cause.', status:'running', phase:'propose', checkpoint:{}, result:null, reason:null, model_calls:3, max_model_calls:24, games_requested:0, max_games:1, reported_cost_usd:0, cost_reports:0, updated_at:'2026-10-02T08:00:00Z'};
const worker = {task_id:taskId,worker_key:'proposal:0',role:'Replay investigator',status:'completed',output:{summary:'Review retreat evidence.'}};
const experiment = {xpRequestId:'xreq_11111111-1111-4111-8111-111111111111',title:'Safer retreats',status:'completed',created_at:'2026-10-02T08:00:00Z',completed_at:'2026-10-02T08:00:00Z',revision:2,completedGames:8,score:42.5,replayReady:true};
let mutations = 0;
let researchReads = 0;
await page.route('**/*', async route => {
  const url = new URL(route.request().url());
  if (url.origin !== new URL(baseURL).origin) return route.abort();
  const send = json => route.fulfill({json});
  if (url.pathname === '/api/session') return send({email:'alice@example.com',name:'Alice',subjectId:'alice'});
  if (url.pathname === '/api/arena') return send({league:{rounds_paused_at:null},episodes:[]});
  if (url.pathname === '/api/policy-stats') return send({policies:[],standings:[],entries:[],entered:[],checkedAt:new Date().toISOString()});
  if (url.pathname === '/api/partner') return send({available:true,claims:[]});
  if (url.pathname === '/api/research') {researchReads++;return send({available:true,cycles:[],events:[],plans:[],evaluations:[],versions:[],experiments:[]});}
  if (url.pathname === '/api/research/autonomy') return send({settings:null});
  if (url.pathname === '/api/chats') return send({chats:[]});
  if (url.pathname === '/api/views') return send({views:[]});
  if (url.pathname === '/api/coaching' || url.pathname === '/api/voice/transcripts') return send({sessions:[]});
  if (url.pathname === '/api/preferences') return send({liveCaptions:true});
  if (url.pathname === '/api/experiments') return send({id:experiment.xpRequestId,title:experiment.title,status:'completed',hypothesis:'Retreat earlier to survive.',counts:{total:8,completed:8,failed:0,scoredSeats:8},episodes:[],meanScore:42.5,policy:null,summary:{},createdAt:experiment.created_at,completedAt:experiment.completed_at,loadedAt:experiment.created_at});
  if (url.pathname.startsWith('/api/')) return route.fulfill({status:404,json:{error:'No fixture'}});
  return route.continue();
});
await page.route('**/api/tasks{,/**,?*}', async route => {
  if (route.request().method() !== 'GET') mutations++;
  return route.fulfill({json:new URL(route.request().url()).pathname === '/api/tasks' ? {tasks:[task], workers:[worker], campaigns:[]} : {task,workers:[worker],sessionIds:[],history:[]}});
});
await page.route('**/api/workspace', route => route.fulfill({json:{versions:[],experiments:[experiment],latest:null,latestUpload:null,player:null,draft:null}}));
try {
  await page.goto(baseURL, {waitUntil:'domcontentloaded'});
  const mode = page.getByRole('navigation', {name:'Workspace mode'});
  const lab = mode.getByRole('button', {name:'Preston’s Lab',exact:true});
  const shared = mode.getByRole('button', {name:'Workspace',exact:true});
  const rail = page.getByRole('region', {name:'Campaigns and sessions'});
  await mode.waitFor();
  assert.equal(await rail.count(), 0);
  assert.equal(researchReads, 0);
  await lab.click();
  await page.getByRole('tab', {name:'Experiments',exact:true}).click();
  await page.getByRole('button', {name:/Safer retreats/}).waitFor();
  assert.equal(await page.getByRole('button', {name:'New experiment',exact:true}).count(),0);

  await mkdir('/tmp/student-harness-lab', {recursive:true});
  await page.screenshot({path:'/tmp/student-harness-lab/workspace.png'});
  await page.getByRole('button', {name:/Safer retreats/}).click();
  await page.getByRole('heading', {name:'Safer retreats',exact:true}).waitFor();
  await page.goBack();
  await page.getByRole('button', {name:/Safer retreats/}).waitFor();
  await lab.click();
  await rail.waitFor();
  await page.getByRole('button', {name:'New experiment',exact:true}).waitFor();
  await rail.getByRole('link', {name:/Investigate early retreats/}).click();
  await page.getByRole('heading', {name:'Investigate early retreats',exact:true}).waitFor();
  assert.match(page.url(),new RegExp('/sessions/'+taskId));
  await page.getByText('Details & workers',{exact:true}).click();
  await page.getByText('Replay investigator',{exact:true}).waitFor();
  await page.screenshot({path:'/tmp/student-harness-lab/lab.png'});
  await shared.click();
  await page.getByRole('heading',{name:'Your policy',exact:true}).waitFor();
  assert.equal(await rail.count(),0);
  assert.equal(await page.getByText('Replay investigator',{exact:true}).count(),0);
  await page.goBack();
  await page.getByRole('heading', {name:'Investigate early retreats',exact:true}).waitFor();
  await page.goForward();
  await page.getByRole('heading',{name:'Your policy',exact:true}).waitFor();
  await page.goto(baseURL+'/sessions/'+taskId,{waitUntil:'domcontentloaded'});
  await page.getByRole('heading', {name:'Investigate early retreats',exact:true}).waitFor();
  assert.equal(await lab.getAttribute('aria-pressed'),'true');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/student-harness-lab/mobile-lab.png'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'No mobile page overflow');
  await shared.click();
  await page.getByRole('heading',{name:'Your policy',exact:true}).waitFor();
  await lab.click();
  await rail.waitFor();
  await page.goto(baseURL+'/?view=lab',{waitUntil:'domcontentloaded'});
  await rail.waitFor();
  assert.equal(await lab.getAttribute('aria-pressed'),'true');
  await page.goto(baseURL+'/?view=episodes',{waitUntil:'domcontentloaded'});
  await page.getByRole('tab',{name:'Episodes',exact:true}).waitFor();
  assert.equal(await lab.getAttribute('aria-pressed'),'true','Episode browser links open Lab');
  assert.equal(mutations,0,'Inspecting views must not launch work');
  assert.deepEqual(errors,[]);
  console.log('PASS: workspace/Lab separation, results, session workers, history, permanent links, mobile, no work launched. Screenshots: /tmp/student-harness-lab');
} finally { await browser.close(); }
