import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const baseURL = process.env.BROWSER_TEST_URL || 'http://localhost:3000';
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
page.setDefaultTimeout(15000);
const errors = []; page.on('pageerror', error => errors.push(error.message));
const league = 'league_3c60897b-25cf-4b37-9d1a-8554c1198f28';
const profiles = ['Tower Power', 'Lane Legend', 'Quiet Storm'].map((name, i) => ({ policyId: `00000000-0000-4000-8000-00000000000${i + 1}`, policyLabel: ['tower:v12', 'lanes:v7', 'storm:v3'][i], playerId: `player-${i}`, playerName: name, rank: i + 1, rating: 24 - i * 3, ratingLabel: 'MMR', episodes: 80 - i * 12, own: false }));
const snapshot = { id: 'snapshot-1', collected_at: '2026-10-07T10:00:00Z', document: { profile: profiles[0], source: 'https://softmax.com/observatory/v2', coverage: 'A sample of 12 league episodes.', episodes: [] } };
const notes = ['Groups three heroes before pushing the middle tower.', 'May overcommit when a side lane is left open.', 'Retreats when the front hero falls below half health.', 'Pressure on both side lanes may split its formation.'].map((text, i) => ({ id: `note-${i}`, kind: i % 2 ? 'hypothesis' : 'observation', actor: 'preston', text, evidence: [{ label: `Round ${100 + i} replay`, url: `https://softmax.com/observatory/v2/episode-requests/ereq_${i}/watch` }], created_at: '2026-10-07T10:15:00Z' }));
const model = { id: 'model-1', created_at: '2026-10-07T10:30:00Z', actor: 'preston', document: { schema: 'gota-opponent-semantic-ir/1', summary: 'A coordinated tower pusher. It groups early, protects its front line, and commits hard to the middle lane. Splitting its attention may create an opening.', nodes: [{ id: 'push', kind: 'strategy', label: 'Push as a group', claim: 'Three heroes move toward the middle tower together.', status: 'observed', evidence: ['e1'] }], edges: [], evidence: [{ id: 'e1', snapshotId: 'snapshot-1', episodeId: 'ereq_1', detail: 'Three heroes enter the lane together at 01:20.' }], unknowns: ['Response to pressure on both side lanes.'], nextTests: ['Probe both side lanes while defending the middle.'] } };
let savedNotes = [...notes]; let failSecond = true; let thirdAnalyzed = false;
const reads = []; const writes = [];
await page.route('**/*', async route => {
  const url = new URL(route.request().url());
  if (url.origin !== new URL(baseURL).origin) return route.abort();
  const send = json => route.fulfill({ json });
  if (url.pathname === '/api/session') return send({ email: 'alice@example.com', name: 'Alice', subjectId: 'alice' });
  if (url.pathname === '/api/workspace') return send({ versions: [], experiments: [], latest: null, latestUpload: null, player: null, draft: null });
  if (url.pathname === '/api/arena') return send({ league: { rounds_paused_at: null }, episodes: [] });
  if (url.pathname === '/api/policy-stats') return send({ policies: [], standings: [], entries: [], entered: [], checkedAt: new Date().toISOString() });
  if (url.pathname === '/api/partner') return send({ available: true, claims: [] });
  if (url.pathname === '/api/research') return send({ available: true, cycles: [], events: [], plans: [], usage: [], evaluations: [] });
  if (url.pathname === '/api/tasks') { if (route.request().method() === 'POST') { writes.push(route.request().postDataJSON()); return send({ task: { id: 'new-task' } }); } return send({ tasks: [], workers: [] }); }
  if (url.pathname === '/api/chats') return send({ chats: [] });
  if (url.pathname === '/api/views') return send({ views: [] });
  if (url.pathname === '/api/coaching' || url.pathname === '/api/voice/transcripts') return send({ sessions: [] });
  if (url.pathname === '/api/preferences') return send({ liveCaptions: true });
  if (url.pathname === '/api/opponents') {
    assert.equal(url.searchParams.get('league'), league);
    const policy = url.searchParams.get('policy');
    if (!policy) return send({ profiles, research: [{policyId: profiles[0].policyId, hasNotes: true, hasModel: true}, ...(thirdAnalyzed ? [{policyId: profiles[2].policyId, hasNotes: true, hasModel: false}] : [])], tracked: [{ policy_id: profiles[0].policyId, collected_at: snapshot.collected_at, profile: profiles[0] }], checkedAt: new Date().toISOString(), leagueURL: 'https://softmax.com/observatory/v2' });
    reads.push(policy);
    if (policy === profiles[1].policyId && failSecond) return route.fulfill({ status: 503, json: { error: 'Unavailable' } });
    return send(policy === profiles[0].policyId ? { snapshots: [snapshot], notes: savedNotes, models: [model], tasks: [], sessions: [] } : { snapshots: [], notes: policy === profiles[2].policyId && thirdAnalyzed ? [{...notes[0], text: 'Quiet Storm prefers the side lanes.'}] : [], models: [], tasks: [], sessions: [] });
  }
  if (url.pathname.startsWith('/api/')) return route.fulfill({ status: 404, json: { error: 'No fixture' } });
  return route.continue();
});
try {
  await page.goto(baseURL);
  await page.getByRole('button',{name:'Preston’s Lab',exact:true}).click();
  await page.getByRole('tab', { name: 'Opponents', exact: true }).click();
  const roster = page.getByRole('region', { name: 'Opponent policies', exact: true });
  const first = roster.getByRole('button', { name: 'Tower Power', exact: true });
  await first.waitFor(); assert.deepEqual(reads, []);
  await first.locator('xpath=ancestor::tr').getByText('Saved analysis', {exact: true}).waitFor();
  assert.equal(await first.getAttribute('aria-expanded'), 'false');
  await first.focus(); await page.keyboard.press('Enter');
  const analysis = roster.getByRole('region', { name: 'Tower Power', exact: true });
  await analysis.getByText(model.document.summary, { exact: true }).first().waitFor();
  await analysis.getByText(notes[0].text, { exact: true }).waitFor();
  assert.equal(await analysis.getByText(notes[3].text, { exact: true }).count(), 0);
  await analysis.getByRole('button', { name: 'Show all 4 notes' }).click();
  await analysis.getByText(notes[3].text, { exact: true }).waitFor();
  assert.equal(await analysis.getByRole('link', { name: 'Round 100 replay' }).getAttribute('href'), notes[0].evidence[0].url);
  await analysis.getByText('Explore semantic model & evidence', { exact: true }).click();
  await analysis.getByRole('heading', { name: 'Push as a group', exact: true }).waitFor();
  await analysis.getByText('Explore semantic model & evidence', { exact: true }).click();
  assert.equal(writes.length, 0, 'Expanding only reads saved research');
  await page.screenshot({ path: '/tmp/opponent-rows-desktop.png' });
  const second = roster.getByRole('button', { name: 'Lane Legend', exact: true });
  await second.click();
  const secondAnalysis = roster.getByRole('region', { name: 'Lane Legend', exact: true });
  await secondAnalysis.getByText('Could not load this opponent’s analysis.', { exact: false }).waitFor();
  failSecond = false; await secondAnalysis.getByRole('button', { name: 'Retry analysis' }).click();
  await secondAnalysis.getByText('No saved analysis yet', { exact: true }).waitFor();
  assert.equal(await first.getAttribute('aria-expanded'), 'true', 'Multiple opponents stay expanded');
  await second.locator('xpath=ancestor::tr').getByRole('button', { name: 'Analyze', exact: true }).click();
  await second.locator('xpath=ancestor::tr').getByRole('button', { name: 'Inspect in Lab ↗' }).waitFor();
  assert.equal(writes.length, 1); assert.equal(writes[0].context.policyId, profiles[1].policyId);
  assert.equal(await second.getAttribute('aria-expanded'), 'true', 'Action buttons do not toggle the row');
  thirdAnalyzed = true;
  savedNotes = [{ ...notes[0], id: 'fresh-note', text: 'Fresh analysis from the latest research session.' }, ...notes];
  await page.evaluate(() => window.dispatchEvent(new Event('opponent-research-updated')));
  await analysis.getByText('Fresh analysis from the latest research session.', { exact: true }).waitFor();
  const third = roster.getByRole('button', { name: 'Quiet Storm', exact: true });
  await third.locator('xpath=ancestor::tr').getByText('Saved analysis', {exact: true}).waitFor();
  assert(!reads.includes(profiles[2].policyId), 'A closed row gets fresh status without fetching its notebook');
  await third.click();
  await roster.getByRole('region', {name: 'Quiet Storm', exact: true}).getByText('Quiet Storm prefers the side lanes.', {exact: true}).waitFor();
  await third.click();
  await first.click(); assert.equal(await analysis.count(), 0);
  await first.locator('xpath=ancestor::tr').getByRole('cell', { name: '#1', exact: true }).click();
  await analysis.getByText(model.document.summary, { exact: true }).first().waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(250); await analysis.scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const mobileAnalysis = await analysis.boundingBox();
  assert(mobileAnalysis.x >= 0 && mobileAnalysis.x + mobileAnalysis.width <= 390, 'Inline analysis fits the mobile viewport');
  await page.screenshot({ path: '/tmp/opponent-rows-mobile.png' });
  await analysis.getByRole('button', { name: 'View full profile ↗', exact: true }).click();
  await roster.getByRole('button', { name: 'Collect latest data' }).waitFor();
  await roster.getByRole('button', { name: '← Opponents' }).click();
  await first.waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: lazy reads, keyboard and row toggles, multiple expanded opponents, saved model/notes/evidence, more notes, independent Analyze action, research refresh, retry, empty state, mobile, full profile navigation.');
} finally { await browser.close(); }
