import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const baseURL = process.env.BROWSER_TEST_URL || 'http://localhost:3000';
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
page.setDefaultTimeout(15000);
const errors = []; page.on('pageerror', e => errors.push(e.message));
const policyId = 'e0000000-0000-4000-8000-000000000088';
let episodeFailure = false;
const outcomes = ['lost', 'time_limit', 'won', 'lost', 'won', 'won', 'time_limit', 'won', 'won', 'won', 'won', 'won'];
const episodes = outcomes.map((outcome, i) => ({ id: `episode-${i}`, status: 'completed', created_at: new Date(Date.UTC(2026, 9, 7, i)).toISOString(), completed_at: new Date(Date.UTC(2026, 9, 7, i, 5)).toISOString(), outcome, score: outcome === 'won' ? 1 : 0, round: { number: i + 100 }, opponents: [{ policy: i % 2 ? 'rival:v2' : 'challenger:v2', player: i % 2 ? 'Rival' : 'Challenger', policyVersionId: 'rival', seats: 5 }], teammates: [], seats: [0, 1, 2, 3, 4], side: 'Red', format: 'team', replay_url: 'https://softmax.com/replay', episode_id: `played-${i}` }));
await page.route('**/*', async route => {
  const url = new URL(route.request().url());
  if (url.origin !== new URL(baseURL).origin) return route.abort();
  const send = json => route.fulfill({ json });
  if (url.pathname === '/api/session') return send({ email: 'alice@example.com', name: 'Alice', subjectId: 'alice' });
  if (url.pathname === '/api/workspace') return send({ versions: [], experiments: [], latest: null, latestUpload: null, player: null, draft: null });
  if (url.pathname === '/api/arena') return send({ league: { rounds_paused_at: null }, episodes: [] });
  if (url.pathname === '/api/policy-stats') return send({ policies: [{ policy_version_id: policyId, player_id: 'player-4', policy_label: 'hero:v8', episodes_played: 12 }], currentPolicyId: policyId, entered: [policyId], entries: [{ policyVersionId: policyId, playerId: 'player-4', playerName: 'Alice', policyLabel: 'hero:v8', active: true, status: 'active' }], standings: Array.from({ length: 12 }, (_, i) => ({ rank: i + 1, player_id: `player-${i}`, player_name: i === 4 ? 'Alice' : ['Arena Champion', 'Tower Power', 'Lane Legend', 'Fort Knox', '', 'Rival', 'Challenger'][i] ?? `Player ${i + 1}`, policy_label: i === 4 ? 'hero:v8' : `arena:v${i + 1}`, score: 24 - i * 1.35, score_label: 'MMR', rounds_played: 40 - i })), checkedAt: new Date().toISOString() });
  if (url.pathname === '/api/league-episodes') return episodeFailure ? route.fulfill({ status: 503, json: { error: 'Fixture unavailable' } }) : send({ policyVersionId: policyId, episodes: [...episodes].reverse(), nextCursor: null });
  if (url.pathname === '/api/league-record') return send({ policyVersionId: policyId, games: 12, wins: 8, losses: 2, time_limits: 2, window_hours: 72, complete: true });
  if (url.pathname === '/api/replay-session') return send({ ready: true, url: `${baseURL}/fixture-replay` });
  if (url.pathname === '/fixture-replay') return route.fulfill({ contentType: 'text/html', body: '<p>Fixture replay</p>' });
  if (url.pathname === '/api/episode-stats') return send({ steps: 100, game_stats: {}, policy_stats: [] });
  if (url.pathname === '/api/partner') return send({ available: true, claims: [] });
  if (url.pathname === '/api/research') return send({ available: true, cycles: [], events: [], plans: [], usage: [], evaluations: [] });
  if (url.pathname === '/api/tasks') return send({ tasks: [], workers: [] });
  if (url.pathname === '/api/chats') return send({ chats: [] });
  if (url.pathname === '/api/views') return send({ views: [] });
  if (url.pathname === '/api/coaching' || url.pathname === '/api/voice/transcripts') return send({ sessions: [] });
  if (url.pathname === '/api/preferences') return send({ liveCaptions: true });
  if (url.pathname.startsWith('/api/')) return route.fulfill({ status: 404, json: { error: 'No fixture' } });
  return route.continue();
});
try {
  await page.goto(baseURL);
  const performance = page.locator('#workspace-performance');
  const recent = performance.getByRole('region', { name: 'Recent outcome trend' });
  await page.getByRole('button',{name:'Preston’s Lab',exact:true}).click();
  await page.getByRole('tab',{name:'Performance',exact:true}).click();
  await recent.getByText('8 wins in 10 completed episodes', { exact: true }).waitFor();
  assert.equal(await recent.getByRole('button', { name: /Open replay/ }).count(), 10);
  assert.match(await recent.getByRole('img').getAttribute('aria-labelledby'), /.+/);
  await page.screenshot({ path: '/tmp/performance-gota-desktop.png' });
  await performance.getByRole('combobox', { name: 'Outcome window' }).click();
  await page.getByRole('option', { name: 'Last 25', exact: true }).click();
  await recent.getByText('8 wins in 12 completed episodes', { exact: true }).waitFor();
  await performance.getByRole('textbox', { name: 'Opponent filter' }).fill('Rival');
  await recent.getByText('4 wins in 6 completed episodes · Rival', { exact: true }).waitFor();
  await recent.getByRole('button', { name: 'Round 111: Win. Open replay', exact: true }).click();
  await page.getByRole('region', { name: 'Selected league replay' }).waitFor();
  await page.getByRole('tab', { name: 'Performance', exact: true }).click();
  await performance.getByRole('textbox', { name: 'Opponent filter' }).fill('Nobody');
  await recent.getByText('No matches against this opponent').waitFor();
  await performance.getByRole('textbox', { name: 'Opponent filter' }).fill('');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(250);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await recent.scrollIntoViewIfNeeded();
  await page.screenshot({ path: '/tmp/performance-gota-mobile.png' });
  episodeFailure = true;
  await page.reload();
  await page.locator('#workspace-performance').getByText('Recent episodes could not load. Use Refresh to retry.', { exact: true }).waitFor();
  episodeFailure = false;
  await page.locator('#workspace-performance').getByRole('button', { name: 'Refresh', exact: true }).click();
  await page.getByRole('region', { name: 'Recent outcome trend' }).getByText('8 wins in 10 completed episodes', { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: current policy, 72-hour wins vs filtered sample, time-limit denominator, chart window and opponent filters, replay navigation, mobile and error recovery.');
} finally { await browser.close(); }
