"use client";
import {useEffect,useState} from 'react';
import {defaultLeagueId} from '../../lib/league-catalog';
import type {OpponentNotebook,OpponentProfile,OpponentResearchStatus} from '../../lib/opponents/model';
import {Input} from '../ui/input';
import {BackgroundButton} from '../tasks/background-button';
import {opponentAnalysisRequest} from '../../lib/opponents/analysis';
import type {AnalysisRequest} from '../chat-context';
import {OpponentModel} from './opponent-model';
import {OpponentRow} from './opponent-row';
import {Textarea} from '../ui/textarea';
type Roster={research?:OpponentResearchStatus[];profiles:OpponentProfile[];tracked:{policy_id:string;collected_at:string;profile:OpponentProfile}[];checkedAt:string;leagueURL:string};
export function Opponents({leagueId=defaultLeagueId,initialPolicyId,onSelect,onDiscuss,onSession,onOpenTask}:{leagueId?:string;initialPolicyId?:string;onSelect?:(id:string|undefined)=>void;onDiscuss?:(text:string)=>void;onSession?:(request:AnalysisRequest)=>void;onOpenTask?:(id:string)=>void}){
 const [roster,setRoster]=useState<Roster|null>(null),[selected,setSelected]=useState(initialPolicyId??''),[book,setBook]=useState<OpponentNotebook|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0),[snapshot,setSnapshot]=useState('');
 useEffect(()=>{setSelected(initialPolicyId??'');},[initialPolicyId]);
 const choose=(id:string)=>{setSelected(id);onSelect?.(id||undefined);};
 useEffect(()=>{const refresh=()=>setTick(n=>n+1);const timer=setInterval(refresh,10000);window.addEventListener('opponent-research-updated',refresh);return()=>{clearInterval(timer);window.removeEventListener('opponent-research-updated',refresh);};},[]);
 const base=`/api/opponents?league=${encodeURIComponent(leagueId)}`;
 useEffect(()=>{const abort=new AbortController();setError('');void fetch(base,{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Could not load opponent policies.');setRoster(await r.json());}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[base,tick]);
 useEffect(()=>{setBook(null);setSnapshot('');},[base,selected]);
 useEffect(()=>{if(!selected)return;const abort=new AbortController();void fetch(`${base}&policy=${encodeURIComponent(selected)}`,{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Could not load this opponent’s records.');setBook(await r.json());}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[base,selected,tick]);
 const tracked=new Map((roster?.tracked??[]).slice().reverse().map(t=>[t.policy_id,t]));
 const profiles=[...(roster?.profiles??[]),...[...tracked.values()].filter(t=>!roster?.profiles.some(p=>p.policyId===t.policy_id)).map(t=>t.profile)].filter((p):p is OpponentProfile=>!!p&&!p.own);
 const profile=profiles.find(p=>p.policyId===selected)??book?.snapshots[0]?.document.profile;
 const current=book?.snapshots.find(s=>s.id===snapshot)??book?.snapshots[0];
 const researchStatus=new Map((roster?.research??[]).map(status=>[status.policyId,status]));
 const matches=profiles.filter(p=>`${p.playerName} ${p.policyLabel}`.toLowerCase().includes(query.toLowerCase()));
 const researchButton=(id:string,label:string,mode:'analyze'|'model',caption:string)=> <BackgroundButton key={`${id}-${mode}`} label={caption} onOpen={onOpenTask} input={{kind:'research',objective:opponentAnalysisRequest(id,label,leagueId,mode).text,acceptanceCriteria:mode==='model'?'Save an evidence-linked semantic model, distinguish observations from hypotheses, and explain unknowns.':'Collect evidence and save sourced observations with useful next tests.',context:{leagueId,policyId:id,mode,title:`${mode==='model'?'Model':'Analyze'} · ${label}`.slice(0,120)}}}/>;
 async function write(input:unknown){setBusy(true);setError('');try{const r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});if(!r.ok)throw Error('Could not save opponent research. Check the evidence link and try again.');setTick(n=>n+1);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <section className="opponents-view" aria-label="Opponent policies">
 {error?<p role="status">{error} <button className="text-button" onClick={()=>setTick(n=>n+1)}>Retry</button></p>:null}
 {!selected?<><header className="opponents-heading"><div><h2>Opponents <small>{profiles.length}</small></h2><p>Expand a row to explore saved analysis, observations, and evidence.</p></div><button className="secondary" onClick={()=>setTick(n=>n+1)}>Refresh league</button></header><Input aria-label="Search opponent policies" placeholder="Find a player or policy" value={query} onChange={e=>setQuery(e.target.value)}/><div className="workspace-table-scroll"><table className="workspace-table opponents-table" aria-label="Opponent policies"><thead><tr><th>Player / policy</th><th>Player rank</th><th>Rating</th><th>Episodes · 72h</th><th>Research</th></tr></thead><tbody>{matches.map(p=><OpponentRow key={`${leagueId}:${p.policyId}`} profile={p} researchStatus={researchStatus.get(p.policyId)} base={base} tick={tick} collectedAt={tracked.get(p.policyId)?.collected_at} live={!!roster?.profiles.some(live=>live.policyId===p.policyId)} onProfile={()=>choose(p.policyId)} onOpenTask={onOpenTask} researchButton={researchButton(p.policyId,p.policyLabel,'analyze','Analyze')}/>)}{!matches.length?<tr><td colSpan={5}>{!roster?'Loading opponents…':query?'No matching policies.':'No opponent policies in the current league sample.'}</td></tr>:null}</tbody></table></div>{roster?<p className="evidence-caption">Player rank and rating are official league standings. Policy activity covers the last 72 hours. <a href={roster.leagueURL} target="_blank" rel="noreferrer">League source ↗</a> · Updated {new Date(roster.checkedAt).toLocaleTimeString()}</p>:null}</>:<>
 <div className="experiment-record-nav"><button className="text-button" onClick={()=>{choose('');setError('');}}>← Opponents</button><a className="text-button" href={`/?view=opponents&opponentPolicy=${selected}${leagueId===defaultLeagueId?'':`&league=${leagueId}`}`}>Page link ↗</a></div>
 <header className="opponents-heading"><div><h2>{profile?.playerName??'Opponent policy'}</h2><p>{profile?.policyLabel??selected}</p></div><button className="secondary" disabled={busy||!roster?.profiles.some(p=>p.policyId===selected)} onClick={()=>void write({action:'collect',policyId:selected})}>{busy?'Saving…':current?'Collect latest data':'Collect data'}</button></header>
 {profile&&!roster?.profiles.some(p=>p.policyId===selected)?<p className="evidence-caption">This version is outside the current policy results. Showing its last collected profile.</p>:null}
 {profile?<div className="experiment-metrics"><div><small>Player rank</small><strong>{profile.rank===null?'—':`#${profile.rank}`}</strong></div><div><small>{profile.ratingLabel??'Rating'}</small><strong>{profile.rating?.toFixed(2)??'—'}</strong></div><div><small>Policy episodes · 72h</small><strong>{profile.episodes}</strong></div><div><small>Saved snapshots</small><strong>{book?.snapshots.length??0}</strong></div></div>:null}
 <div className="opponent-session-actions">{researchButton(selected,profile?.policyLabel??selected,'analyze','Analyze opponent')}{researchButton(selected,profile?.policyLabel??selected,'model',book?.models?.length?'Refine semantic model':'Build semantic model')}<small>Runs in a background session.</small></div>
 {!book?<p>Loading research…</p>:<>
 {book.tasks?.length?<section className="opponent-sessions"><h3>Background sessions</h3>{book.tasks.map(t=><div key={t.id}><button className="text-button" disabled={!onOpenTask} onClick={()=>onOpenTask?.(t.id)}>{t.context?.title??t.objective.split('\n')[0]} ↗</button><small>{t.status}</small></div>)}</section>:null}
 <OpponentModel models={book.models??[]} snapshots={book.snapshots}/>
 {book.sessions?.length?<section className="opponent-sessions"><h3>Earlier conversations</h3>{book.sessions.map(s=><div key={s.session_id}><button className="text-button" disabled={!onSession} onClick={()=>onSession?.({id:Date.now(),text:'',sessionId:s.session_id})}>{s.title??'Opponent research'} ↗</button><small>{new Date(s.updated_at).toLocaleString()}</small></div>)}</section>:null}
 {current?<section className="opponent-evidence"><div className="workspace-section-heading"><h3>Collected evidence</h3><select aria-label="Opponent snapshot" value={current.id} onChange={e=>setSnapshot(e.target.value)}>{book.snapshots.map(s=><option key={s.id} value={s.id}>{new Date(s.collected_at).toLocaleString()}</option>)}</select></div><p className="evidence-caption">{current.document.coverage}</p>{current.document.warning?<p role="status" className="opponent-collection-note">{current.document.warning}</p>:null}<p className="evidence-caption">At collection: player rank {current.document.profile.rank===null?'unknown':`#${current.document.profile.rank}`} · {current.document.profile.rating?.toFixed(2)??'—'} {current.document.profile.ratingLabel}. <a href={current.document.source} target="_blank" rel="noreferrer">Source ↗</a></p><div className="workspace-table-scroll"><table className="workspace-table" aria-label="Opponent episodes"><thead><tr><th>Round</th><th>Status</th><th>Policy seat scores</th><th>Evidence</th></tr></thead><tbody>{current.document.episodes.map(e=><tr key={e.id}><td>#{e.round}</td><td>{e.status}</td><td>{e.scores.length?e.scores.map(s=>`${s.score.toFixed(2)} (seat ${s.position})`).join(', '):'—'}</td><td><a href={`https://softmax.com/observatory/v2/episode-requests/${e.id}/watch`} target="_blank" rel="noreferrer">{e.replay?'Replay':'Episode'} ↗</a><details><summary>Participants</summary>{e.participants.map(p=><p key={p.position}>{p.player_name??p.policy_name??p.policy_version_id??'Unknown'} · seat {p.position}</p>)}</details></td></tr>)}{!current.document.episodes.length?<tr><td colSpan={4}>{current.document.warning?'Episode evidence is incomplete.':'No matching episodes in this sample. This does not mean the policy has never played.'}</td></tr>:null}</tbody></table></div></section>:<p className="opponent-empty">Collect data to save this policy’s current league standing and recent episode evidence.</p>}
 <section className="opponent-notes"><h3>Observations & hypotheses</h3>{book.notes.map(n=><article key={n.id}><small>{n.kind} · {n.actor==='preston'?'Preston':'You'} · {new Date(n.created_at).toLocaleString()}</small><p>{n.text}</p>{n.evidence.map((e,i)=><a key={i} href={e.url} target="_blank" rel="noreferrer">{e.label} ↗</a>)}</article>)}{!book.notes.length?<p className="muted">No observations recorded yet.</p>:null}
 {current?<details><summary>Add an observation or hypothesis</summary><form className="opponent-note-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await write({action:'note',policyId:selected,note:{kind:f.get('kind'),text:f.get('text'),evidence:[{label:f.get('label'),url:f.get('url')}]}}))form.reset();}}><label>Type<select name="kind" aria-label="Observation type"><option value="observation">Observation</option><option value="hypothesis">Hypothesis</option></select></label><label>What did you notice?<Textarea name="text" required minLength={8} maxLength={3000}/></label><label>Evidence label<Input name="label" required maxLength={200} placeholder="Round or replay moment"/></label><label>Softmax evidence link<Input name="url" type="url" required defaultValue={current.document.source}/></label><button className="secondary" disabled={busy}>Save note</button></form></details>:null}</section>
 </>}

 </>}
 </section>;
}
