"use client";
import {useMemo,useState,type ReactNode} from 'react';
import type {PolicyRevision} from '../../lib/semantic-ir';
import {policyWikiEntries,searchWikiEntries,wikiPages,wikiPageLabels,type WikiPage,type WikiKind} from '../../lib/workspace/policy-wiki';
import {SemanticPolicy} from '../semantic-policy';
import {presentationRoute} from '../../lib/workspace/presentation';
import {Input} from '../ui/input';

type Props={revision:PolicyRevision|null;page:WikiPage;onPage:(page:WikiPage)=>void;entryId?:string;onEntry:(id:string)=>void;branchId?:string;onBranch:(id:string)=>void;onDiscuss:(text:string)=>void;revisionPicker:ReactNode;actions:ReactNode;versions:ReactNode;beliefs:ReactNode;experiments:{xpRequestId:string;title:string;status:string;revision:number|null}[];onExperiment:(id:string)=>void;leagueURL:string};
const descriptions:Record<WikiKind,string>={situation:'Conditions and observations the policy can use.',belief:'Recorded hypotheses with their status and evidence.',goal:'Objectives, including authored intent and interpretations.',skill:'Named operators and the actions they intend to perform.',strategy:'Rules connecting a situation to skills and goals.',execution:'Language, source binding, and exact source identity.',update:'Parent revision, changes, evidence, and the research plan.'};
export function WikiFields({value}:{value:unknown}){
 if(value==null||(typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===0))return <span className="wiki-empty-value">None recorded</span>;
 if(Array.isArray(value))return value.length?<ul className="wiki-field-list">{value.map((v,i)=><li key={i}><WikiFields value={v}/></li>)}</ul>:<span className="wiki-empty-value">None recorded</span>;
 if(typeof value==='object')return <dl className="wiki-fields">{Object.entries(value as Record<string,unknown>).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd><WikiFields value={v}/></dd></div>)}</dl>;
 return <span>{String(value)}</span>;
}
export function PolicyWiki({revision,page,onPage,entryId,onEntry,branchId,onBranch,onDiscuss,revisionPicker,actions,versions,beliefs,experiments,onExperiment,leagueURL}:Props){
 const [query,setQuery]=useState(''),[kind,setKind]=useState<WikiKind|'all'>('all');
 const entries=useMemo(()=>revision?policyWikiEntries(revision):[],[revision]);
 const visible=searchWikiEntries(entries,query).filter(e=>kind==='all'||kind===e.kind);
 const selected=entries.find(e=>e.key===entryId);
 const related=selected?entries.filter(e=>e.links.some(link=>link.key===selected.key)):[];
 const ir=revision?.ir;
 const choose=(id:string)=>{setKind('all');setQuery('');onEntry(id);onPage('ontology');};
 const inspectSource=(id:string)=>{onBranch(id);onPage('source');};
 const counts=(k:WikiKind)=>entries.filter(e=>e.kind===k).length;
 const link=presentationRoute({view:'development',last:10,reason:'Policy wiki',wikiPage:page,entityId:entryId,branchId:page==='source'?branchId:undefined,...(ir?.update.revision?{revision:ir.update.revision}:{})});
 return <section className="policy-wiki" aria-label="Policy wiki">
   <header className="wiki-header"><div><h2>Policy wiki</h2><p>{ir?`hero.bas · ${ir.update.revision?`r${ir.update.revision}`:'starter'} · semantic and symbolic records`:'Loading policy records…'}</p></div><div className="wiki-header-actions">{revisionPicker}<a className="text-button" href={link} title="Open a link to this wiki page">Page link ↗</a>{actions}</div></header>
   <div className="wiki-layout"><nav className="wiki-navigation" aria-label="Policy wiki sections">{wikiPages.map(p=><button key={p} type="button" aria-current={page===p?'page':undefined} onClick={()=>onPage(p)}>{wikiPageLabels[p]}</button>)}</nav>
   <article className="wiki-article" aria-label={wikiPageLabels[page]}>
   {page==='overview'?<><h3>Policy record</h3><p>{ir?.update.change??'Loading the current revision…'}</p><div className="wiki-directory">{(['situation','belief','goal','skill','strategy','execution','update'] as WikiKind[]).map(k=><button key={k} onClick={()=>{setKind(k);setQuery('');onEntry('');onPage('ontology');}}><strong>{k[0].toUpperCase()+k.slice(1)} <small>{counts(k)}</small></strong><span>{descriptions[k]}</span></button>)}</div><section className="wiki-explainer"><h4>How the structures connect</h4><div className="wiki-chain"><button onClick={()=>{setKind('situation');onPage('ontology');}}>Situation</button><span>→</span><button onClick={()=>{setKind('strategy');onPage('ontology');}}>Strategy rule</button><span>→</span><button onClick={()=>{setKind('skill');onPage('ontology');}}>Skill</button><span>→</span><button onClick={()=>onPage('source')}>Source</button></div><p>Strategy rules reference conditions, skills and goals. Beliefs have their own evidence records; this schema does not yet store explicit belief-to-rule links.</p></section><div className="wiki-overview-links"><button className="text-button" onClick={()=>onPage('beliefs')}>Beliefs and disagreements ↗</button><button className="text-button" onClick={()=>onPage('evidence')}>Verification and experiments ↗</button></div></>:null}
   {page==='ontology'?<><h3>Semantic ontology</h3><p>Definitions and relations stored in this revision. Select an object to inspect all of its fields.</p><div className="wiki-search"><Input aria-label="Search semantic ontology" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a concept, condition, action, or ID"/><select aria-label="Ontology layer" value={kind} onChange={e=>setKind(e.target.value as WikiKind|'all')}><option value="all">All layers</option>{Object.keys(descriptions).map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select><span>{visible.length} objects</span></div><div className="wiki-ontology"><nav className="wiki-object-list" aria-label="Ontology objects">{visible.map(e=><button key={e.key} aria-current={selected?.key===e.key?'true':undefined} onClick={()=>choose(e.key)}><small>{e.kind} · {e.id}</small><span>{e.summary}</span></button>)}{!visible.length?<p>No matching objects.</p>:null}</nav><section className="wiki-object-detail" aria-label="Ontology object">{selected?<><div className="wiki-object-heading"><span className="eyebrow">{selected.kind}</span><h4>{selected.id}</h4></div><WikiFields value={selected.fields}/>{selected.links.length?<div className="wiki-relations"><h4>References</h4>{selected.links.map(l=><button className="text-button" key={l.key} onClick={()=>choose(l.key)}>{l.label} ↗</button>)}</div>:null}{related.length?<div className="wiki-relations"><h4>Used by</h4>{related.map(e=><button className="text-button" key={e.key} onClick={()=>choose(e.key)}>{e.id} ↗</button>)}</div>:null}{selected.ruleId?<button className="secondary" onClick={()=>inspectSource(selected.ruleId!)}>Inspect mapped source ↗</button>:null}<button className="text-button wiki-discuss" onClick={()=>onDiscuss(`Inspect the ${selected.kind} object ${selected.id} in policy revision r${ir?.update.revision}: ${selected.summary}. Read the stored fields and evidence. Explain its role, uncertainties and what we could test or improve.`)}>Discuss this object ↗</button></>:<p>{entryId?'This object is not present in the selected revision.':'Choose an object to inspect its definition and links.'}</p>}</section></div><details className="wiki-raw"><summary>Complete semantic IR · JSON</summary><pre>{ir?JSON.stringify(ir,null,2):'Loading…'}</pre></details></>:null}
   {page==='beliefs'?<><h3>Beliefs & lessons</h3><section className="wiki-revision-beliefs"><h4>Beliefs recorded in {ir?.update.revision?`r${ir.update.revision}`:'the starter'}</h4>{entries.filter(e=>e.kind==='belief').map(e=><button key={e.key} className="wiki-belief" onClick={()=>choose(e.key)}><code>{e.id}</code><strong>{e.summary}</strong><span>{ir?.belief.claims[e.id].status.replaceAll('_',' ')} · {ir?.belief.claims[e.id].evidence.length} evidence references ↗</span></button>)}{!counts('belief')?<p>No beliefs recorded in this revision.</p>:null}</section><section className="wiki-shared-beliefs"><h4>Shared workspace · current beliefs and disagreements</h4>{beliefs}</section></>:null}
   {page==='source'?<><h3>Symbolic source</h3><p>The complete BASIC program and its semantic source mappings. A source link records intended behavior, not a verified runtime trace.</p>{revision?<SemanticPolicy key={revision.revisionId} revision={revision} selectedRuleId={branchId}/>:<p>Loading hero.bas…</p>}</>:null}
   {page==='versions'?<><h3>Version history</h3>{versions}</>:null}
   {page==='evidence'?<><h3>Evidence & verification</h3>{revision?<><h4>Verification receipts · r{ir!.update.revision}</h4><WikiFields value={revision.receipts}/><h4>Research plan</h4><WikiFields value={ir!.update.research_plan}/><h4>Recorded evidence references</h4><WikiFields value={ir!.update.evidence}/><h4>Source identity</h4><WikiFields value={{revisionId:revision.revisionId,parent:ir!.update.parent,source_sha256:ir!.execution.source_sha256}}/></>:null}<h4>Hosted experiments for this revision</h4><div className="workspace-table-scroll"><table className="workspace-table"><thead><tr><th>Experiment</th><th>Status</th></tr></thead><tbody>{experiments.filter(e=>e.revision===ir?.update.revision).map(e=><tr key={e.xpRequestId}><td><button className="text-button" onClick={()=>onExperiment(e.xpRequestId)}>{e.title} ↗</button></td><td>{e.status}</td></tr>)}{!experiments.some(e=>e.revision===ir?.update.revision)?<tr><td colSpan={2}>No hosted experiments linked to this revision.</td></tr>:null}</tbody></table></div></>:null}
   {page==='reference'?<><h3>Game reference</h3><div className="wiki-reference-list"><a href="https://softmax.com/gods-of-the-arena/wiki/overview" target="_blank" rel="noreferrer"><strong>Game rules ↗</strong><span>Live rules and mechanics.</span></a><a href="https://softmax.com/gods-of-the-arena/wiki/policy-and-host-surface" target="_blank" rel="noreferrer"><strong>Policy and host API ↗</strong><span>Available observations, actions, and BASIC host functions.</span></a><a href={leagueURL} target="_blank" rel="noreferrer"><strong>League ↗</strong><span>Current standings, entries, and rounds.</span></a></div><h4>Observation authority</h4><p>{ir?.situation.authority}</p><h4>Recorded unknowns</h4><WikiFields value={ir?.situation.unknowns??[]}/></>:null}
   </article></div>
 </section>;
}
