"use client";
import { useEffect,useState } from 'react';
import { transcriptTurns,type VoiceEvent } from '../../lib/voice/transcript';
import { ChevronRightIcon } from 'lucide-react';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { SelectField } from '@/components/ui/select-field';
export function VoiceHistory() {
  const [open,setOpen]=useState(false),[sessions,setSessions]=useState<{id:string;started_at:string}[]>([]),[selected,setSelected]=useState(''),[events,setEvents]=useState<VoiceEvent[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{if(!open)return;const abort=new AbortController();void fetch('/api/voice/transcripts',{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error();setSessions((await r.json()).sessions);setError('');}).catch(()=>{if(!abort.signal.aborted)setError('Conversation history is unavailable.');});return()=>abort.abort();},[open]);
  useEffect(()=>{if(!selected)return;const abort=new AbortController();setEvents([]);setLoading(true);setError('');void(async()=>{let after=-1;const all:VoiceEvent[]=[];do{const r=await fetch(`/api/voice/transcripts?session=${encodeURIComponent(selected)}&after=${after}`,{signal:abort.signal});if(!r.ok)throw Error();const d=await r.json();all.push(...d.events);after=d.next??-1;}while(after!==-1);if(!abort.signal.aborted)setEvents(all);})().catch(()=>{if(!abort.signal.aborted)setError('Transcript could not be loaded.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[selected,open]);
  function download(){const blob=new Blob([JSON.stringify({session:selected,events},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='preston-conversation.json';a.click();URL.revokeObjectURL(url);}
  return <Collapsible className="voice-history" open={open} onOpenChange={setOpen}><CollapsibleTrigger><ChevronRightIcon className="size-3" aria-hidden />Voice history</CollapsibleTrigger><CollapsibleContent>{open?<><SelectField aria-label="Voice conversation" value={selected} onValueChange={setSelected} placeholder="Choose a conversation" options={sessions.map(s=>({value:s.id,label:new Date(s.started_at).toLocaleString()}))}/>{error?<p role="status">{error}</p>:loading?<p>Loading transcript…</p>:selected?<><div className="voice-transcript">{transcriptTurns(events).map((t,i)=><p key={i}><strong>{t.role==='user'?'You':'Preston'}</strong><time>{t.start===null?'':`${Math.floor(t.start/60000)}:${String(Math.floor(t.start/1000)%60).padStart(2,'0')}`}</time><span>{t.text}</span></p>)}</div><button className="text-button" onClick={download}>Download transcript and tool log</button></>:!sessions.length?<p>No saved voice conversations yet.</p>:null}</>:null}</CollapsibleContent></Collapsible>;
}
