type Campaign = {id:string;task_id:string;objective:string;state:string;phase:string;cycle:number};
type Work = {id:string;status:string;context?:Record<string,unknown>|null;result?:unknown;updated_at:string};
const phases:Record<string,string>={research:'I’m looking for clues in our replays.',build:'I’m building a candidate from what we learned.',screen:'I’m comparing our latest candidate.',confirm:'I’m checking whether the improvement holds up.',confirmation:'I’m checking whether the improvement holds up.',freeze:'I’m preparing a fair comparison.',deploy:'I’m updating our league policy.',baseline:'I’m checking where we’re starting from.',synthesize:'I’m bringing our findings together.',promote:'I’m updating our league policy.',observe:'I’m watching how we do in the league.',bootstrap:'I’m getting our research started.',done:'Our results are ready to explore.'};
export function campaignCompanion(campaign:Campaign|undefined,tasks:Work[],stale=false){
 if(!campaign)return {status:null,title:null,finding:null,sourceId:null};
 const root=tasks.find(t=>t.id===campaign.task_id);
 const state=root?.status??campaign.state;
 const status=stale?'We can explore our saved findings while updates reconnect.':state==='needs_input'?'I could use your perspective on our next step.':state==='paused'?'Our campaign is paused. We can pick it up together.':state==='failed'?'Our research hit a snag. Let’s take a look.':state==='canceled'?'This campaign has stopped. What should we explore next?':state==='completed'?'Our results are ready. Let’s see what we learned.':phases[campaign.phase]??'I’m working on our next experiment.';
 const latest=tasks.filter(t=>t.context?.campaignId===campaign.id&&t.status==='completed'&&typeof (t.result as {summary?:unknown}|null)?.summary==='string'&&!!(t.result as {summary:string}).summary.trim()).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))[0];
 const clean=(text:string)=>text.replace(/\s*\([^)]*league_[^)]*\)/g,'').replace(/league_[a-zA-Z0-9-]+/g,'').replace(/\s+/g,' ').trim();
 const excerpt=(text:string,max:number)=>text.length>max?text.slice(0,max).replace(/\s+\S*$/,'')+'…':text;
 return {status,title:excerpt(clean(campaign.objective),180),finding:latest?excerpt(clean((latest.result as {summary:string}).summary),260):null,sourceId:latest?.id??null};
}
export function companionPrompts(view:string,hasCampaign:boolean,hasFinding:boolean){
 const contextual:Record<string,{label:string;text:string}>={episodes:{label:'Walk me through this replay',text:'Walk me through the replay or episode I’m viewing. Help me understand one important decision, using the actual evidence.'},opponents:{label:'What can we learn from them?',text:'What can we learn from the opponent I’m viewing? Distinguish observed behavior from hypotheses.'},strategy:{label:'Explain our approach',text:'Explain our current policy strategy and its most important tradeoff.'},development:{label:'What do we believe so far?',text:'Explain one important belief in our policy wiki and the evidence behind it.'},experiments:{label:'What are we trying next?',text:'What are we trying next in our experiments, and what would we learn from it?'},performance:{label:'How are we doing?',text:'How are we doing in the selected league? Check current evidence and explain what matters.'}};
 return [contextual[view]??contextual.performance,hasCampaign?{label:hasFinding?'What did we learn?':'What are you exploring?',text:hasFinding?'Explain our latest campaign finding and link to the evidence. What does it mean for our policy?':'What is our campaign investigating now, and why?'}:{label:'Help me choose a direction',text:'Help me choose a useful research direction based on our current policy and league evidence.'}];
}
